version: 2.1

defaults: &defaults
  working_directory: ~/example-ember-component-library
  docker:
    - image: circleci/node:8-browsers
  environment:
    CHROME_BIN: "/usr/bin/google-chrome"
    JOBS: 1 # https://github.com/emberjs/ember.js/issues/15641

jobs:
  build-test:
    <<: *defaults  
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies
      - run:
          name: Install all packages
          command: yarn
      - run:
          name: Run the linter on the template files
          command: yarn lint:hbs
      - run:
          name: Run the linter on the javascript & typescript files
          command: yarn lint:js
      - run:
          name: Run the first test
          command: yarn test
      - run:
          name: Run Danger.JS
          command: yarn danger ci
      - save_cache:
          paths:
              - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ./
          paths:
              - ./

  integration-tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Run all of the tests
          command: yarn test:all

  deploy-docs:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./
      - add_ssh_keys:
          fingerprints:
              - "30:d0:d8:ca:49:89:d5:89:c0:ef:0f:91:91:4b:1c:f1"
      - run:
          name: Deploy this version of the docs
          command: DEPLOY_KEY=`cat ~/.ssh/id_rsa` yarn deploy

  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./
      - run: 
          name: Authenticate with NPM registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/example-ember-component-library/.npmrc
      - run:
          name: Publish package
          command: npx semantic-release


workflows:
  eecl:
    jobs:
      - build-test:
          context: maingot
          filters:
            branches:
              only: /.*/
            tags:
              only: /^v.*/

      - integration-tests:
          context: maingot
          requires:
            - build-test
          filters:
            branches:
              only: /master/

      - deploy-docs:
          context: maingot
          requires:
            - build-test
          filters:
            branches:
              only: /.*/
            tags:
              only: /^v.*/

      - publish:
          context: maingot
          requires:
            - build-test
            - integration-tests
            - deploy-docs
          filters:
            branches:
              only: /master/
