version: 2.1

defaults: &defaults
  working_directory: ~/example-ember-component-library
  docker:
    - image: circleci/node:8-browsers-legacy

jobs:
  build:
    <<: *defaults  
    steps:
      - checkout

      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "yarn.lock" }}
      #       - v1-dependencies

      - run:
          name: Install all packages
          command: yarn

      - run:
          name: Run the linter on the template files
          command: yarn lint:hbs

      - run:
          name: Run the linter on the javascript files
          command: yarn lint:js

      - run:
          name: Run the first test
          command: yarn test

      - run:
          name: Run all of the tests
          command: yarn test:all

      - run:
          name: Build the package
          command: yarn build

      - run:
          name: Deploy this version of the docs
          command: yarn deploy

      # - save_cache:
      #     paths:
      #         - node_modules
      #     key: v1-dependencies-{{ checksum "yarn.lock" }}

      - persist_to_workspace:
          root: ./
          paths:
              - ./

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./
      - run: 
          name: Authenticate with NPM registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish


workflows:
  eecl:
    jobs:
      - build:
          context: maingot
          filters:
            branches:
              only: /.*/
            tags:
              only: /^v.*/
      - deploy:
          context: maingot
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
